import React, { createContext, useContext, useState, useEffect } from "react";

type Language = {
  code: string;
  name: string;
  nativeName: string;
};

export const languages: Language[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
];

type TranslationsType = {
  [key: string]: {
    [key: string]: string;
  };
};

// Sample translations for demonstration purposes
const translations: TranslationsType = {
  // Document edit translations
  "document.edit.title": {
    en: "Edit Document",
    de: "Dokument bearbeiten",
    fr: "Modifier le document",
    es: "Editar documento",
    it: "Modifica documento",
    sk: "Upraviť dokument",
    cs: "Upravit dokument",
    hu: "Dokumentum szerkesztése",
    pl: "Edytuj dokument",
    pt: "Editar documento",
    hi: "दस्तावेज़ संपादित करें",
    zh: "编辑文档",
    ja: "ドキュメントを編集",
  },
  "document.edit.name": {
    en: "Document Name",
    de: "Dokumentname",
    fr: "Nom du document",
    es: "Nombre del documento",
    it: "Nome del documento",
    sk: "Názov dokumentu",
    cs: "Název dokumentu",
    hu: "Dokumentum neve",
    pl: "Nazwa dokumentu",
    pt: "Nome do documento",
    hi: "दस्तावेज़ का नाम",
    zh: "文档名称",
    ja: "ドキュメント名",
  },
  "document.edit.description": {
    en: "Description",
    de: "Beschreibung",
    fr: "Description",
    es: "Descripción",
    it: "Descrizione",
    sk: "Popis",
    cs: "Popis",
    hu: "Leírás",
    pl: "Opis",
    pt: "Descrição",
    hi: "विवरण",
    zh: "描述",
    ja: "説明",
  },
  "document.edit.type": {
    en: "Document Type",
    de: "Dokumenttyp",
    fr: "Type de document",
    es: "Tipo de documento",
    it: "Tipo di documento",
    sk: "Typ dokumentu",
    cs: "Typ dokumentu",
    hu: "Dokumentum típusa",
    pl: "Typ dokumentu",
    pt: "Tipo de documento",
    hi: "दस्तावेज़ प्रकार",
    zh: "文档类型",
    ja: "ドキュメントタイプ",
  },
  "document.edit.content": {
    en: "Document Content",
    de: "Dokumentinhalt",
    fr: "Contenu du document",
    es: "Contenido del documento",
    it: "Contenuto del documento",
    sk: "Obsah dokumentu",
    cs: "Obsah dokumentu",
    hu: "Dokumentum tartalma",
    pl: "Zawartość dokumentu",
    pt: "Conteúdo do documento",
    hi: "दस्तावेज़ सामग्री",
    zh: "文档内容",
    ja: "ドキュメント内容",
  },
  "document.edit.save": {
    en: "Save Changes",
    de: "Änderungen speichern",
    fr: "Enregistrer les modifications",
    es: "Guardar cambios",
    it: "Salva modifiche",
    sk: "Uložiť zmeny",
    cs: "Uložit změny",
    hu: "Változtatások mentése",
    pl: "Zapisz zmiany",
    pt: "Salvar alterações",
    hi: "परिवर्तन सहेजें",
    zh: "保存更改",
    ja: "変更を保存",
  },
  "document.edit.cancel": {
    en: "Cancel",
    de: "Abbrechen",
    fr: "Annuler",
    es: "Cancelar",
    it: "Annulla",
    sk: "Zrušiť",
    cs: "Zrušit",
    hu: "Mégsem",
    pl: "Anuluj",
    pt: "Cancelar",
    hi: "रद्द करें",
    zh: "取消",
    ja: "キャンセル",
  },
  "document.edit.template": {
    en: "Select Template",
    de: "Vorlage auswählen",
    fr: "Sélectionner un modèle",
    es: "Seleccionar plantilla",
    it: "Seleziona modello",
    sk: "Vyberte šablónu",
    cs: "Vyberte šablonu",
    hu: "Sablon kiválasztása",
    pl: "Wybierz szablon",
    pt: "Selecionar modelo",
    hi: "टेम्पलेट चुनें",
    zh: "选择模板",
    ja: "テンプレートを選択",
  },
  "document.edit.preview": {
    en: "Preview Template",
    de: "Vorschau der Vorlage",
    fr: "Aperçu du modèle",
    es: "Vista previa de la plantilla",
    it: "Anteprima del modello",
    sk: "Náhľad šablóny",
    cs: "Náhled šablony",
    hu: "Sablon előnézete",
    pl: "Podgląd szablonu",
    pt: "Visualizar modelo",
    hi: "टेम्पलेट प्रिव्यू",
    zh: "预览模板",
    ja: "テンプレートプレビュー",
  },
  "common.back": {
    en: "Back",
    de: "Zurück",
    fr: "Retour",
    es: "Volver",
    it: "Indietro",
    sk: "Späť",
    cs: "Zpět",
    hu: "Vissza",
    pl: "Powrót",
    pt: "Voltar",
    hi: "वापस",
    zh: "返回",
    ja: "戻る",
  },
  // Document types
  "document.types.household": {
    en: "Household",
    de: "Haushalt",
    fr: "Ménage",
    es: "Hogar",
    it: "Casa",
    sk: "Domácnosť",
    cs: "Domácnost",
    hu: "Háztartás",
    pl: "Gospodarstwo domowe",
    pt: "Lar",
    hi: "घरेलू",
    zh: "家庭",
    ja: "家庭",
  },
  "document.types.finance": {
    en: "Finance",
    de: "Finanzen",
    fr: "Finance",
    es: "Finanzas",
    it: "Finanza",
    sk: "Financie",
    cs: "Finance",
    hu: "Pénzügy",
    pl: "Finanse",
    pt: "Finanças",
    hi: "वित्त",
    zh: "财务",
    ja: "金融",
  },
  "document.types.crypto": {
    en: "Cryptocurrency",
    de: "Kryptowährung",
    fr: "Cryptomonnaie",
    es: "Criptomoneda",
    it: "Criptovaluta",
    sk: "Kryptomena",
    cs: "Kryptoměna",
    hu: "Kriptovaluta",
    pl: "Kryptowaluta",
    pt: "Criptomoeda",
    hi: "क्रिप्टोकरेंसी",
    zh: "加密货币",
    ja: "暗号通貨",
  },
  "document.types.family": {
    en: "Family",
    de: "Familie",
    fr: "Famille",
    es: "Familia",
    it: "Famiglia",
    sk: "Rodina",
    cs: "Rodina",
    hu: "Család",
    pl: "Rodzina",
    pt: "Família",
    hi: "परिवार",
    zh: "家族",
    ja: "家族",
  },
  "document.types.instructions": {
    en: "Instructions",
    de: "Anweisungen",
    fr: "Instructions",
    es: "Instrucciones",
    it: "Istruzioni",
    sk: "Inštrukcie",
    cs: "Instrukce",
    hu: "Utasítások",
    pl: "Instrukcje",
    pt: "Instruções",
    hi: "निर्देश",
    zh: "指示",
    ja: "手順",
  },
  // Editor translations
  "editor.visualMode": {
    en: "Visual Editor",
    de: "Visueller Editor",
    fr: "Éditeur visuel",
    es: "Editor visual",
    it: "Editor visivo",
    sk: "Vizuálny editor",
    cs: "Vizuální editor",
    hu: "Vizuális szerkesztő",
    pl: "Edytor wizualny",
    pt: "Editor visual",
    hi: "विज़ुअल एडिटर",
    zh: "可视化编辑器",
    ja: "ビジュアルエディタ",
  },
  "editor.markdownMode": {
    en: "Markdown",
    de: "Markdown",
    fr: "Markdown",
    es: "Markdown",
    it: "Markdown",
    sk: "Markdown",
    cs: "Markdown",
    hu: "Markdown",
    pl: "Markdown",
    pt: "Markdown",
    hi: "मार्कडाउन",
    zh: "Markdown",
    ja: "マークダウン",
  },
  "editor.default": {
    en: "Default",
    de: "Standard",
    fr: "Par défaut",
    es: "Predeterminado",
    it: "Predefinito",
    sk: "Predvolené",
    cs: "Výchozí",
    hu: "Alapértelmezett",
    pl: "Domyślny",
    pt: "Padrão",
    hi: "डिफॉल्ट",
    zh: "默认",
    ja: "デフォルト",
  },
  "editor.red": {
    en: "Red",
    de: "Rot",
    fr: "Rouge",
    es: "Rojo",
    it: "Rosso",
    sk: "Červená",
    cs: "Červená",
    hu: "Piros",
    pl: "Czerwony",
    pt: "Vermelho",
    hi: "लाल",
    zh: "红色",
    ja: "赤",
  },
  "editor.blue": {
    en: "Blue",
    de: "Blau",
    fr: "Bleu",
    es: "Azul",
    it: "Blu",
    sk: "Modrá",
    cs: "Modrá",
    hu: "Kék",
    pl: "Niebieski",
    pt: "Azul",
    hi: "नीला",
    zh: "蓝色",
    ja: "青",
  },
  "editor.green": {
    en: "Green",
    de: "Grün",
    fr: "Vert",
    es: "Verde",
    it: "Verde",
    sk: "Zelená",
    cs: "Zelená",
    hu: "Zöld",
    pl: "Zielony",
    pt: "Verde",
    hi: "हरा",
    zh: "绿色",
    ja: "緑",
  },
  "editor.yellow": {
    en: "Yellow",
    de: "Gelb",
    fr: "Jaune",
    es: "Amarillo",
    it: "Giallo",
    sk: "Žltá",
    cs: "Žlutá",
    hu: "Sárga",
    pl: "Żółty",
    pt: "Amarelo",
    hi: "पीला",
    zh: "黄色",
    ja: "黄色",
  },
  "editor.purple": {
    en: "Purple",
    de: "Lila",
    fr: "Violet",
    es: "Púrpura",
    it: "Viola",
    sk: "Fialová",
    cs: "Fialová",
    hu: "Lila",
    pl: "Fioletowy",
    pt: "Roxo",
    hi: "बैंगनी",
    zh: "紫色",
    ja: "紫",
  },
  "document.edit.savedDescription": {
    en: "Your document has been saved successfully",
    de: "Ihr Dokument wurde erfolgreich gespeichert",
    fr: "Votre document a été enregistré avec succès",
    es: "Su documento ha sido guardado exitosamente",
    it: "Il tuo documento è stato salvato con successo",
    sk: "Váš dokument bol úspešne uložený",
    cs: "Váš dokument byl úspěšně uložen",
    hu: "A dokumentumot sikeresen elmentettük",
    pl: "Twój dokument został pomyślnie zapisany",
    pt: "Seu documento foi salvo com sucesso",
    hi: "आपका दस्तावेज़ सफलतापूर्वक सहेजा गया है",
    zh: "您的文档已成功保存",
    ja: "ドキュメントが正常に保存されました",
  },
  "document.edit.saved": {
    en: "Document Saved",
    de: "Dokument gespeichert",
    fr: "Document enregistré",
    es: "Documento guardado",
    it: "Documento salvato",
    sk: "Dokument uložený",
    cs: "Dokument uložen",
    hu: "Dokumentum mentve",
    pl: "Dokument zapisany",
    pt: "Documento salvo",
    hi: "दस्तावेज़ सहेज लिया गया",
    zh: "文档已保存",
    ja: "ドキュメントが保存されました",
  },
  "document.edit.templateApplied": {
    en: "Template Applied",
    de: "Vorlage angewendet",
    fr: "Modèle appliqué",
    es: "Plantilla aplicada",
    it: "Modello applicato",
    sk: "Šablóna aplikovaná",
    cs: "Šablona použita",
    hu: "Sablon alkalmazva",
    pl: "Szablon zastosowany",
    pt: "Modelo aplicado",
    hi: "टेम्पलेट लागू किया गया",
    zh: "已应用模板",
    ja: "テンプレートが適用されました",
  },
  "document.edit.templateAppliedDescription": {
    en: "Template has been applied",
    de: "Die Vorlage wurde angewendet",
    fr: "Le modèle a été appliqué",
    es: "La plantilla ha sido aplicada",
    it: "Il modello è stato applicato",
    sk: "Šablóna bola aplikovaná",
    cs: "Šablona byla použita",
    hu: "A sablon alkalmazva lett",
    pl: "Szablon został zastosowany",
    pt: "O modelo foi aplicado",
    hi: "टेम्पलेट लागू कर दिया गया है",
    zh: "模板已被应用",
    ja: "テンプレートが適用されました",
  },
  "document.edit.attachments": {
    en: "Attachments",
    de: "Anhänge",
    fr: "Pièces jointes",
    es: "Archivos adjuntos",
    it: "Allegati",
    sk: "Prílohy",
    cs: "Přílohy",
    hu: "Mellékletek",
    pl: "Załączniki",
    pt: "Anexos",
    hi: "अनुलग्नक",
    zh: "附件",
    ja: "添付ファイル",
  },
  "document.edit.attachFile": {
    en: "Attach File",
    de: "Datei anhängen",
    fr: "Joindre un fichier",
    es: "Adjuntar archivo",
    it: "Allega file",
    sk: "Priložiť súbor",
    cs: "Připojit soubor",
    hu: "Fájl csatolása",
    pl: "Dołącz plik",
    pt: "Anexar arquivo",
    hi: "फ़ाइल अनुलग्न करें",
    zh: "附加文件",
    ja: "ファイルを添付",
  },
  "document.edit.insertIntoDocument": {
    en: "Insert into document",
    de: "In Dokument einfügen",
    fr: "Insérer dans le document",
    es: "Insertar en el documento",
    it: "Inserisci nel documento",
    sk: "Vložiť do dokumentu",
    cs: "Vložit do dokumentu",
    hu: "Beszúrás a dokumentumba",
    pl: "Wstaw do dokumentu",
    pt: "Inserir no documento",
    hi: "दस्तावेज में डालें",
    zh: "插入到文档",
    ja: "ドキュメントに挿入",
  },
  "document.edit.removeAttachment": {
    en: "Remove attachment",
    de: "Anhang entfernen",
    fr: "Supprimer la pièce jointe",
    es: "Eliminar archivo adjunto",
    it: "Rimuovi allegato",
    sk: "Odstrániť prílohu",
    cs: "Odstranit přílohu",
    hu: "Melléklet eltávolítása",
    pl: "Usuń załącznik",
    pt: "Remover anexo",
    hi: "अनुलग्नक हटाएं",
    zh: "删除附件",
    ja: "添付ファイルを削除",
  },
  "document.lastUpdated": {
    en: "Last updated",
    de: "Zuletzt aktualisiert",
    fr: "Dernière mise à jour",
    es: "Última actualización",
    it: "Ultimo aggiornamento",
    sk: "Aktualizované",
    cs: "Aktualizováno",
    hu: "Utoljára frissítve",
    pl: "Ostatnia aktualizacja",
    pt: "Última atualização",
    hi: "आखरी अपडेट",
    zh: "最后更新",
    ja: "最終更新",
  },
  "document.recipients": {
    en: "{count} recipients",
    de: "{count} Empfänger",
    fr: "{count} destinataires",
    es: "{count} destinatarios",
    it: "{count} destinatari",
    sk: "{count} príjemcov",
    cs: "{count} příjemců",
    hu: "{count} címzett",
    pl: "{count} odbiorców",
    pt: "{count} destinatários",
    hi: "{count} प्राप्तकर्ता",
    zh: "{count} 收件人",
    ja: "{count} 受信者",
  },
  "document.attachments": {
    en: "{count} files",
    de: "{count} Dateien",
    fr: "{count} fichiers",
    es: "{count} archivos",
    it: "{count} file",
    sk: "{count} súborov",
    cs: "{count} souborů",
    hu: "{count} fájl",
    pl: "{count} plików",
    pt: "{count} arquivos",
    hi: "{count} फ़ाइलें",
    zh: "{count} 文件",
    ja: "{count} ファイル",
  },
  "document.list.title": {
    en: "My Documents",
    de: "Meine Dokumente",
    fr: "Mes Documents",
    es: "Mis Documentos",
    it: "I miei Documenti",
    sk: "Moje Dokumenty",
    cs: "Moje Dokumenty",
    hu: "Dokumentumaim",
    pl: "Moje Dokumenty",
    pt: "Meus Documentos",
    hi: "मेरे दस्तावेज़",
    zh: "我的文档",
    ja: "マイドキュメント",
  },
  "document.encrypted": {
    en: "Encrypted",
    sk: "Šifrované",
    cs: "Šifrované",
  },
  "document.open": {
    en: "Open",
    sk: "Otvoriť",
    cs: "Otevřít",
  },
  "document.edit": {
    en: "Edit document",
    sk: "Upraviť dokument",
    cs: "Upravit dokument",
  },
  "document.delete": {
    en: "Delete document",
    sk: "Vymazať dokument",
    cs: "Smazat dokument",
  },
  // Home page translations
  "home.hero.title": {
    en: "Secure information for your loved ones",
    de: "Sichere Informationen für Ihre Lieben",
    fr: "Sécurisez les informations pour vos proches",
    es: "Información segura para sus seres queridos",
    it: "Informazioni sicure per i tuoi cari",
    sk: "Zabezpečte informácie pre svojich blízkych",
    cs: "Zabezpečte informace pro své blízké",
    hu: "Biztonságos információk szerettei számára",
    pl: "Zabezpiecz informacje dla swoich bliskich",
    pt: "Informações seguras para seus entes queridos",
    hi: "अपने प्रियजनों के लिए सुरक्षित जानकारी",
    zh: "为您的亲人提供安全信息",
    ja: "愛する人のための安全な情報",
  },
  "home.hero.subtitle": {
    en: "Life Key ensures that your important documents and information are available to your loved ones in case of emergency or long-term inactivity.",
    de: "Life Key sorgt dafür, dass Ihre wichtigen Dokumente und Informationen für Ihre Lieben im Notfall oder bei längerer Inaktivität verfügbar sind.",
    fr: "Life Key garantit que vos documents et informations importants sont disponibles pour vos proches en cas d'urgence ou d'inactivité prolongée.",
    es: "Life Key garantiza que sus documentos e información importantes estén disponibles para sus seres queridos en caso de emergencia o inactividad a largo plazo.",
    it: "Life Key assicura che i tuoi documenti e le informazioni importanti siano disponibili per i tuoi cari in caso di emergenza o inattività a lungo termine.",
    sk: "Životný kľúč sa postará, aby vaše dôležité dokumenty a informácie boli dostupné vašim bližným v prípade núdzovej situácie alebo dlhodobej neaktivity.",
    cs: "Životní klíč se postará o to, aby vaše důležité dokumenty a informace byly dostupné vašim blízkým v případě nouzové situace nebo dlouhodobé nečinnosti.",
    hu: "Az Életkulcs gondoskodik arról, hogy fontos dokumentumai és információi elérhetők legyenek szerettei számára vészhelyzet vagy hosszú távú inaktivitás esetén.",
    pl: "Klucz Życia dba o to, aby ważne dokumenty i informacje były dostępne dla Twoich bliskich w sytuacji awaryjnej lub długotrwałej nieaktywności.",
    pt: "A Chave da Vida garante que seus documentos e informações importantes estejam disponíveis para seus entes queridos em caso de emergência ou inatividade de longo prazo.",
    hi: "लाइफ की यह सुनिश्चित करती है कि आपके महत्वपूर्ण दस्तावेज और जानकारी आपातकालीन स्थिति या लंबी अवधि की निष्क्रियता के मामले में आपके प्रियजनों के लिए उपलब्ध हों।",
    zh: "生命密钥确保在紧急情况或长期不活动的情况下，您的重要文件和信息可供您的亲人使用。",
    ja: "ライフキーは、緊急時や長期間の不活動の場合に、重要な文書や情報が愛する人に提供されることを保証します。",
  },
  "home.button.getStarted": {
    en: "Get Started",
    de: "Loslegen",
    fr: "Commencer",
    es: "Empezar",
    it: "Iniziare",
    sk: "Začať teraz",
    cs: "Začít teď",
    hu: "Kezdés",
    pl: "Rozpocznij",
    pt: "Começar",
    hi: "शुरू करें",
    zh: "开始使用",
    ja: "始める",
  },
  "home.button.howItWorks": {
    en: "How It Works",
    de: "Wie es funktioniert",
    fr: "Comment ça marche",
    es: "Cómo funciona",
    it: "Come funziona",
    sk: "Ako to funguje",
    cs: "Jak to funguje",
    hu: "Hogyan működik",
    pl: "Jak to działa",
    pt: "Como funciona",
    hi: "यह कैसे काम करता है",
    zh: "它是如何工作的",
    ja: "仕組み",
  },
  "home.features.title": {
    en: "Practical solution for you and your loved ones",
    de: "Praktische Lösung für Sie und Ihre Lieben",
    fr: "Solution pratique pour vous et vos proches",
    es: "Solución práctica para usted y sus seres queridos",
    it: "Soluzione pratica per te e i tuoi cari",
    sk: "Praktické riešenie pre vás a vašich blízkych",
    cs: "Praktické řešení pro vás a vaše blízké",
    hu: "Praktikus megoldás Önnek és szeretteinek",
    pl: "Praktyczne rozwiązanie dla Ciebie i Twoich bliskich",
    pt: "Solução prática para você e seus entes queridos",
    hi: "आपके और आपके प्रियजनों के लिए व्यावहारिक समाधान",
    zh: "为您和您的亲人提供实用的解决方案",
    ja: "あなたとあなたの大切な人のための実用的なソリューション",
  },
  "home.features.subtitle": {
    en: "Ensure that your loved ones are prepared for any situation with complete information.",
    de: "Stellen Sie sicher, dass Ihre Lieben mit vollständigen Informationen auf jede Situation vorbereitet sind.",
    fr: "Assurez-vous que vos proches sont préparés à toute situation avec des informations complètes.",
    es: "Asegúrese de que sus seres queridos estén preparados para cualquier situación con información completa.",
    it: "Assicurati che i tuoi cari siano preparati a qualsiasi situazione con informazioni complete.",
    sk: "Zabezpečte, že vaši blízki budú pripravení na akúkoľvek situáciu s kompletnými informáciami.",
    cs: "Zajistěte, aby vaši blízcí byli připraveni na jakoukoli situaci s kompletními informacemi.",
    hu: "Gondoskodjon arról, hogy szerettei teljes információkkal felkészüljenek bármilyen helyzetre.",
    pl: "Zapewnij, aby Twoi bliscy byli przygotowani na każdą sytuację z kompletnymi informacjami.",
    pt: "Garanta que seus entes queridos estejam preparados para qualquer situação com informações completas.",
    hi: "सुनिश्चित करें कि आपके प्रियजन पूर्ण जानकारी के साथ किसी भी स्थिति के लिए तैयार हैं।",
    zh: "确保您的亲人有完整的信息准备应对任何情况。",
    ja: "あなたの大切な人が完全な情報で、どんな状況にも備えられるようにしてください。",
  },
  "home.feature.documents": {
    en: "Organized Documents",
    de: "Organisierte Dokumente",
    fr: "Documents organisés",
    es: "Documentos organizados",
    it: "Documenti organizzati",
    sk: "Organizované dokumenty",
    cs: "Organizované dokumenty",
    hu: "Szervezett dokumentumok",
    pl: "Zorganizowane dokumenty",
    pt: "Documentos organizados",
    hi: "संगठित दस्तावेज़",
    zh: "组织文件",
    ja: "整理された文書",
  },
  "home.feature.documents.description": {
    en: "Create categorized documents with instructions, access information, and guidelines for various life situations.",
    de: "Erstellen Sie kategorisierte Dokumente mit Anweisungen, Zugangsinformationen und Richtlinien für verschiedene Lebenssituationen.",
    fr: "Créez des documents catégorisés avec des instructions, des informations d'accès et des directives pour diverses situations de la vie.",
    es: "Cree documentos categorizados con instrucciones, información de acceso y pautas para diversas situaciones de la vida.",
    it: "Crea documenti categorizzati con istruzioni, informazioni di accesso e linee guida per varie situazioni di vita.",
    sk: "Vytvorte kategorizované dokumenty s inštrukciami, prístupovými údajmi a pokynmi pre rôzne životné situácie.",
    cs: "Vytvořte kategorizované dokumenty s pokyny, přístupovými údaji a pokyny pro různé životní situace.",
    hu: "Hozzon létre kategorizált dokumentumokat utasításokkal, hozzáférési információkkal és irányelvekkel különböző élethelyzetekre.",
    pl: "Twórz skategoryzowane dokumenty z instrukcjami, informacjami dostępowymi i wytycznymi dla różnych sytuacji życiowych.",
    pt: "Crie documentos categorizados com instruções, informações de acesso e diretrizes para várias situações da vida.",
    hi: "विभिन्न जीवन परिस्थितियों के लिए निर्देशों, पहुंच जानकारी और दिशानिर्देशों के साथ श्रेणीबद्ध दस्तावेज़ बनाएं।",
    zh: "为各种生活情况创建分类文件，包含说明、访问信息和指南。",
    ja: "さまざまな生活状況に対する指示、アクセス情報、ガイドラインを含む分類されたドキュメントを作成します。",
  },
  "home.feature.activity": {
    en: "Activity Monitoring",
    de: "Aktivitätsüberwachung",
    fr: "Surveillance de l'activité",
    es: "Monitoreo de actividad",
    it: "Monitoraggio dell'attività",
    sk: "Kontrola aktivity",
    cs: "Kontrola aktivity",
    hu: "Tevékenység figyelése",
    pl: "Monitorowanie aktywności",
    pt: "Monitoramento de atividade",
    hi: "गतिविधि निगरानी",
    zh: "活动监控",
    ja: "アクティビティ監視",
  },
  "home.feature.activity.description": {
    en: "The system automatically monitors your activity and responds only in case of long-term inactivity.",
    de: "Das System überwacht automatisch Ihre Aktivität und reagiert nur bei langfristiger Inaktivität.",
    fr: "Le système surveille automatiquement votre activité et ne réagit qu'en cas d'inactivité prolongée.",
    es: "El sistema monitorea automáticamente su actividad y responde solo en caso de inactividad a largo plazo.",
    it: "Il sistema monitora automaticamente la tua attività e risponde solo in caso di inattività a lungo termine.",
    sk: "Systém automaticky kontroluje vašu aktivitu a reaguje len v prípade dlhodobej neaktivity.",
    cs: "Systém automaticky sleduje vaši aktivitu a reaguje pouze v případě dlouhodobé nečinnosti.",
    hu: "A rendszer automatikusan figyeli az Ön tevékenységét, és csak hosszú távú inaktivitás esetén reagál.",
    pl: "System automatycznie monitoruje twoją aktywność i reaguje tylko w przypadku długotrwałej nieaktywności.",
    pt: "O sistema monitora automaticamente sua atividade e responde apenas em caso de inatividade de longo prazo.",
    hi: "सिस्टम स्वचालित रूप से आपकी गतिविधि की निगरानी करता है और केवल दीर्घकालिक निष्क्रियता के मामले में प्रतिक्रिया देता है।",
    zh: "系统会自动监控您的活动，并且只有在长期不活动的情况下才会响应。",
    ja: "システムは自動的にあなたの活動を監視し、長期間の非アクティブな場合にのみ対応します。",
  },
  "home.feature.contacts": {
    en: "Trusted Contacts",
    de: "Vertrauenswürdige Kontakte",
    fr: "Contacts de confiance",
    es: "Contactos de confianza",
    it: "Contatti fidati",
    sk: "Dôveryhodné kontakty",
    cs: "Důvěryhodné kontakty",
    hu: "Megbízható kapcsolatok",
    pl: "Zaufane kontakty",
    pt: "Contatos confiáveis",
    hi: "विश्वसनीय संपर्क",
    zh: "可信联系人",
    ja: "信頼できる連絡先",
  },
  "home.feature.contacts.description": {
    en: "Add trusted people who will receive access to your information after meeting security conditions.",
    de: "Fügen Sie vertrauenswürdige Personen hinzu, die nach Erfüllung der Sicherheitsbedingungen Zugriff auf Ihre Informationen erhalten.",
    fr: "Ajoutez des personnes de confiance qui auront accès à vos informations après avoir rempli les conditions de sécurité.",
    es: "Agregue personas de confianza que recibirán acceso a su información después de cumplir con las condiciones de seguridad.",
    it: "Aggiungi persone fidate che riceveranno l'accesso alle tue informazioni dopo aver soddisfatto le condizioni di sicurezza.",
    sk: "Pridajte dôveryhodné osoby, ktoré dostanú prístup k vašim informáciám po splnení bezpečnostných podmienok.",
    cs: "Přidejte důvěryhodné osoby, které získají přístup k vašim informacím po splnění bezpečnostních podmínek.",
