
import React, { createContext, useContext, useState } from 'react';

type Language = 'sk' | 'en' | 'de' | 'cs';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; name: string; nativeName: string; }[];
}

const languages = [
  { code: 'sk' as Language, name: 'Slovak', nativeName: 'Slovenčina' },
  { code: 'en' as Language, name: 'English', nativeName: 'English' },
  { code: 'de' as Language, name: 'German', nativeName: 'Deutsch' },
  { code: 'cs' as Language, name: 'Czech', nativeName: 'Čeština' },
];

const translations = {
  sk: {
    "home.hero.title": "Zabezpečte svoje digitálne dedičstvo",
    "home.hero.subtitle": "Životný kľúč vám umožňuje bezpečne uchovávať a zdieľať dôležité informácie s vami vybranými osobami v prípade núdze.",
    "home.button.getStarted": "Začať používať",
    "home.button.howItWorks": "Ako to funguje",
    "home.features.title": "Komplexné riešenie pre vaše digitálne dedičstvo",
    "home.features.subtitle": "Životný kľúč poskytuje všetky nástroje, ktoré potrebujete na zabezpečenie vašich digitálnych aktív a informácií.",
    "home.feature.documents": "Bezpečné dokumenty",
    "home.feature.documents.description": "Vytvárajte a spravujte šifrované dokumenty s dôležitými informáciami:",
    "home.feature.activity": "Kontrola aktivity",
    "home.feature.activity.description": "Pravidelné overovanie vašej aktivity zabezpečí, že vaše informácie zostanú v bezpečí:",
    "home.feature.contacts": "Správa príjemcov",
    "home.feature.contacts.description": "Definujte, kto a za akých okolností získa prístup k vašim dokumentom:",
    "home.howItWorks.title": "Ako Životný kľúč funguje",
    "home.howItWorks.subtitle": "Jednoduchý a bezpečný proces v troch krokoch",
    "home.step.one": "Vytvorte dokumenty",
    "home.step.one.description": "Vytvorte dokumenty s dôležitými informáciami, prístupovými údajmi a inštrukciami.",
    "home.step.two": "Nastavte príjemcov",
    "home.step.two.description": "Určite, kto má mať prístup ku ktorým dokumentom v prípade núdze.",
    "home.step.three": "Pravidelne potvrdzujte",
    "home.step.three.description": "Systém vás bude pravidelne kontaktovať. Pri dlhodobej neaktivite sa spustí bezpečnostný protokol.",
    "home.blog.title": "Najnovšie články",
    "home.blog.subtitle": "Prečítajte si naše najnovšie články o digitálnom dedičstve a bezpečnosti",
    "home.blog.viewAll": "Zobraziť všetky články",
    "home.cta.title": "Zabezpečte svoje digitálne dedičstvo ešte dnes",
    "home.cta.subtitle": "Vytvorte si účet a začnite chrániť svoje digitálne aktíva a informácie pre vašich blízkych.",
    "home.cta.freeAccount": "Vytvoriť bezplatný účet",
    "home.cta.premium": "Zobraziť prémiové funkcie",
    "document.list.title": "Moje dokumenty",
    "document.types.household": "Domácnosť",
    "document.types.finance": "Financie",
    "document.types.crypto": "Kryptomeny",
    "document.types.family": "Rodina",
    "document.types.instructions": "Inštrukcie",
    "document.edit.title": "Upraviť dokument",
    "document.edit.name": "Názov dokumentu",
    "document.edit.description": "Popis dokumentu",
    "document.edit.type": "Typ dokumentu",
    "document.edit.template": "Použiť šablónu",
    "document.edit.content": "Obsah dokumentu",
    "document.edit.cancel": "Zrušiť",
    "document.edit.save": "Uložiť zmeny",
    "document.edit.saved": "Dokument uložený",
    "document.edit.savedDescription": "Váš dokument bol úspešne uložený.",
    "document.edit.templateApplied": "Šablóna aplikovaná",
    "document.edit.templateAppliedDescription": "Obsah dokumentu bol aktualizovaný podľa šablóny",
    "common.back": "Späť",

    // Account page
    "account.title": "Môj účet",
    "account.personalInfo": "Osobné údaje",
    "account.name": "Meno a priezvisko",
    "account.email": "Email",
    "account.phone": "Telefónne číslo",
    "account.subscription": "Plán predplatného",
    "account.editProfile": "Upraviť profil",
    "account.security": "Bezpečnosť",
    "account.password": "Heslo",
    "account.lastChanged": "Naposledy zmenené",
    "account.2fa": "Dvojfaktorové overenie",
    "account.active": "Aktívne",
    "account.changePassword": "Zmeniť heslo",
    "account.2faSettings": "Nastavenia 2FA",
    "account.settings": "Nastavenia",
    "account.notifications": "Notifikácie a upozornenia",
    "account.privacy": "Súkromie a zdieľanie",
    "account.phoneVerification": "Overenie telefónu",
    "account.subscriptionStatus": "Predplatné",
    "account.validUntil": "Platné do",
    "account.manageSubscription": "Spravovať predplatné",

    // Contact page
    "contact.title": "Kontaktujte nás",
    "contact.subtitle": "Máte otázky alebo potrebujete pomoc? Vyplňte kontaktný formulár a my sa vám ozveme čo najskôr.",
    "contact.form.name": "Vaše meno",
    "contact.form.email": "Váš email",
    "contact.form.subject": "Predmet",
    "contact.form.message": "Vaša správa",
    "contact.form.submit": "Odoslať správu",
    "contact.form.success": "Správa odoslaná",
    "contact.form.successMessage": "Ďakujeme za vašu správu. Odpovieme čo najskôr.",
    "contact.office": "Prevádzkové hodiny",
    "contact.workdays": "Pondelok - Piatok",
    "contact.weekend": "Sobota - Nedeľa",
    "contact.closed": "Zatvorené",

    // Documentation page
    "docs.title": "Dokumentácia a návody",
    "docs.subtitle": "Naša dokumentácia vám pomôže využiť plný potenciál služby Životný kľúč.",
    "docs.gettingStarted": "Začíname so službou",
    "docs.account": "Vytvorenie účtu a prvé kroky",
    "docs.2fa": "Nastavenie dvojfaktorovej autentifikácie",
    "docs.firstDoc": "Vytvorenie prvého dokumentu",
    "docs.recipient": "Pridanie príjemcu",
    "docs.management": "Správa dokumentov",
    "docs.types": "Typy dokumentov a ich použitie",
    "docs.templates": "Šablóny pre rôzne účely",
    "docs.encryption": "Šifrovanie a bezpečnosť dokumentov",
    "docs.organization": "Organizácia dokumentov",

    // FAQ page
    "faq.title": "Časté otázky",
    "faq.noResponse": "Čo sa stane, ak nereagujem na kontrolnú správu?",
    "faq.noResponseAnswer": "Ak nereagujete na kontrolnú správu, systém sa pokúsi kontaktovať vami opakovane rôznymi kanálmi (e-mail, SMS). Ak nebudete reagovať po definovanú dobu, spustí sa bezpečnostný protokol.",
    "faq.frequency": "Ako často budem dostávať kontrolné správy?",
    "faq.frequencyAnswer": "Frekvenciu kontrolných správ si môžete nastaviť podľa vlastných preferencií. Štandardne je nastavená na každých 30 dní.",
  },
  en: {
    "home.hero.title": "Secure Your Digital Legacy",
    "home.hero.subtitle": "Life Key allows you to securely store and share important information with your chosen recipients in case of emergency.",
    "home.button.getStarted": "Get Started",
    "home.button.howItWorks": "How It Works",
    "home.features.title": "Comprehensive Solution for Your Digital Legacy",
    "home.features.subtitle": "Life Key provides all the tools you need to secure your digital assets and information.",
    "home.feature.documents": "Secure Documents",
    "home.feature.documents.description": "Create and manage encrypted documents with important information:",
    "home.feature.activity": "Activity Monitoring",
    "home.feature.activity.description": "Regular verification of your activity ensures that your information remains secure:",
    "home.feature.contacts": "Recipient Management",
    "home.feature.contacts.description": "Define who and under what circumstances will gain access to your documents:",
    "home.howItWorks.title": "How Life Key Works",
    "home.howItWorks.subtitle": "Simple and secure process in three steps",
    "home.step.one": "Create Documents",
    "home.step.one.description": "Create documents with important information, access credentials, and instructions.",
    "home.step.two": "Set Recipients",
    "home.step.two.description": "Determine who should have access to which documents in case of emergency.",
    "home.step.three": "Regular Check-ins",
    "home.step.three.description": "The system will contact you regularly. In case of prolonged inactivity, the security protocol will be activated.",
    "home.blog.title": "Latest Articles",
    "home.blog.subtitle": "Read our latest articles about digital legacy and security",
    "home.blog.viewAll": "View All Articles",
    "home.cta.title": "Secure Your Digital Legacy Today",
    "home.cta.subtitle": "Create an account and start protecting your digital assets and information for your loved ones.",
    "home.cta.freeAccount": "Create Free Account",
    "home.cta.premium": "View Premium Features",
    "document.list.title": "My Documents",
    "document.types.household": "Household",
    "document.types.finance": "Finance",
    "document.types.crypto": "Cryptocurrency",
    "document.types.family": "Family",
    "document.types.instructions": "Instructions",
    "document.edit.title": "Edit Document",
    "document.edit.name": "Document Name",
    "document.edit.description": "Document Description",
    "document.edit.type": "Document Type",
    "document.edit.template": "Use Template",
    "document.edit.content": "Document Content",
    "document.edit.cancel": "Cancel",
    "document.edit.save": "Save Changes",
    "document.edit.saved": "Document Saved",
    "document.edit.savedDescription": "Your document has been successfully saved.",
    "document.edit.templateApplied": "Template Applied",
    "document.edit.templateAppliedDescription": "Document content has been updated based on the template",
    "common.back": "Back",

    // Account page
    "account.title": "My Account",
    "account.personalInfo": "Personal Information",
    "account.name": "Full Name",
    "account.email": "Email",
    "account.phone": "Phone Number",
    "account.subscription": "Subscription Plan",
    "account.editProfile": "Edit Profile",
    "account.security": "Security",
    "account.password": "Password",
    "account.lastChanged": "Last Changed",
    "account.2fa": "Two-Factor Authentication",
    "account.active": "Active",
    "account.changePassword": "Change Password",
    "account.2faSettings": "2FA Settings",
    "account.settings": "Settings",
    "account.notifications": "Notifications and Alerts",
    "account.privacy": "Privacy and Sharing",
    "account.phoneVerification": "Phone Verification",
    "account.subscriptionStatus": "Subscription",
    "account.validUntil": "Valid Until",
    "account.manageSubscription": "Manage Subscription",

    // Contact page
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions or need help? Fill out the contact form and we'll get back to you as soon as possible.",
    "contact.form.name": "Your Name",
    "contact.form.email": "Your Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Your Message",
    "contact.form.submit": "Send Message",
    "contact.form.success": "Message Sent",
    "contact.form.successMessage": "Thank you for your message. We will respond as soon as possible.",
    "contact.office": "Office Hours",
    "contact.workdays": "Monday - Friday",
    "contact.weekend": "Saturday - Sunday",
    "contact.closed": "Closed",

    // Documentation page
    "docs.title": "Documentation and Guides",
    "docs.subtitle": "Our documentation will help you use Life Key to its full potential.",
    "docs.gettingStarted": "Getting Started",
    "docs.account": "Creating an Account and First Steps",
    "docs.2fa": "Setting up Two-Factor Authentication",
    "docs.firstDoc": "Creating Your First Document",
    "docs.recipient": "Adding a Recipient",
    "docs.management": "Document Management",
    "docs.types": "Document Types and Their Use",
    "docs.templates": "Templates for Various Purposes",
    "docs.encryption": "Encryption and Document Security",
    "docs.organization": "Document Organization",

    // FAQ page
    "faq.title": "Frequently Asked Questions",
    "faq.noResponse": "What happens if I don't respond to the check-in message?",
    "faq.noResponseAnswer": "If you don't respond to the check-in message, the system will try to contact you repeatedly through various channels (email, SMS). If you don't respond within the defined period, the security protocol will be activated.",
    "faq.frequency": "How often will I receive check-in messages?",
    "faq.frequencyAnswer": "You can set the frequency of check-in messages according to your preferences. By default, it is set to every 30 days.",
  },
  de: {
    "home.hero.title": "Sichern Sie Ihr digitales Erbe",
    "home.hero.subtitle": "Life Key ermöglicht es Ihnen, wichtige Informationen sicher zu speichern und mit ausgewählten Empfängern im Notfall zu teilen.",
    "home.button.getStarted": "Jetzt starten",
    "home.button.howItWorks": "Wie es funktioniert",
    "home.features.title": "Umfassende Lösung für Ihr digitales Erbe",
    "home.features.subtitle": "Life Key bietet alle Werkzeuge, die Sie benötigen, um Ihre digitalen Vermögenswerte und Informationen zu sichern.",
    "home.feature.documents": "Sichere Dokumente",
    "home.feature.documents.description": "Erstellen und verwalten Sie verschlüsselte Dokumente mit wichtigen Informationen:",
    "home.feature.activity": "Aktivitätsüberwachung",
    "home.feature.activity.description": "Regelmäßige Überprüfung Ihrer Aktivität stellt sicher, dass Ihre Informationen sicher bleiben:",
    "home.feature.contacts": "Empfängerverwaltung",
    "home.feature.contacts.description": "Legen Sie fest, wer und unter welchen Umständen Zugriff auf Ihre Dokumente erhält:",
    "home.howItWorks.title": "Wie Life Key funktioniert",
    "home.howItWorks.subtitle": "Einfacher und sicherer Prozess in drei Schritten",
    "home.step.one": "Dokumente erstellen",
    "home.step.one.description": "Erstellen Sie Dokumente mit wichtigen Informationen, Zugangsdaten und Anweisungen.",
    "home.step.two": "Empfänger festlegen",
    "home.step.two.description": "Bestimmen Sie, wer im Notfall Zugriff auf welche Dokumente haben soll.",
    "home.step.three": "Regelmäßige Überprüfungen",
    "home.step.three.description": "Das System wird Sie regelmäßig kontaktieren. Bei längerer Inaktivität wird das Sicherheitsprotokoll aktiviert.",
    "home.blog.title": "Neueste Artikel",
    "home.blog.subtitle": "Lesen Sie unsere neuesten Artikel über digitales Erbe und Sicherheit",
    "home.blog.viewAll": "Alle Artikel anzeigen",
    "home.cta.title": "Sichern Sie Ihr digitales Erbe noch heute",
    "home.cta.subtitle": "Erstellen Sie ein Konto und beginnen Sie, Ihre digitalen Vermögenswerte und Informationen für Ihre Lieben zu schützen.",
    "home.cta.freeAccount": "Kostenloses Konto erstellen",
    "home.cta.premium": "Premium-Funktionen anzeigen",
    "document.list.title": "Meine Dokumente",
    "document.types.household": "Haushalt",
    "document.types.finance": "Finanzen",
    "document.types.crypto": "Kryptowährung",
    "document.types.family": "Familie",
    "document.types.instructions": "Anweisungen",
    "document.edit.title": "Dokument bearbeiten",
    "document.edit.name": "Dokumentname",
    "document.edit.description": "Dokumentbeschreibung",
    "document.edit.type": "Dokumenttyp",
    "document.edit.template": "Vorlage verwenden",
    "document.edit.content": "Dokumentinhalt",
    "document.edit.cancel": "Abbrechen",
    "document.edit.save": "Änderungen speichern",
    "document.edit.saved": "Dokument gespeichert",
    "document.edit.savedDescription": "Ihr Dokument wurde erfolgreich gespeichert.",
    "document.edit.templateApplied": "Vorlage angewendet",
    "document.edit.templateAppliedDescription": "Dokumentinhalt wurde basierend auf der Vorlage aktualisiert",
    "common.back": "Zurück",

    // Account page
    "account.title": "Mein Konto",
    "account.personalInfo": "Persönliche Informationen",
    "account.name": "Vollständiger Name",
    "account.email": "E-Mail",
    "account.phone": "Telefonnummer",
    "account.subscription": "Abonnementplan",
    "account.editProfile": "Profil bearbeiten",
    "account.security": "Sicherheit",
    "account.password": "Passwort",
    "account.lastChanged": "Zuletzt geändert",
    "account.2fa": "Zwei-Faktor-Authentifizierung",
    "account.active": "Aktiv",
    "account.changePassword": "Passwort ändern",
    "account.2faSettings": "2FA-Einstellungen",
    "account.settings": "Einstellungen",
    "account.notifications": "Benachrichtigungen und Warnungen",
    "account.privacy": "Datenschutz und Freigabe",
    "account.phoneVerification": "Telefonverifizierung",
    "account.subscriptionStatus": "Abonnement",
    "account.validUntil": "Gültig bis",
    "account.manageSubscription": "Abonnement verwalten",

    // Contact page
    "contact.title": "Kontakt",
    "contact.subtitle": "Haben Sie Fragen oder brauchen Sie Hilfe? Füllen Sie das Kontaktformular aus und wir melden uns so schnell wie möglich bei Ihnen.",
    "contact.form.name": "Ihr Name",
    "contact.form.email": "Ihre E-Mail",
    "contact.form.subject": "Betreff",
    "contact.form.message": "Ihre Nachricht",
    "contact.form.submit": "Nachricht senden",
    "contact.form.success": "Nachricht gesendet",
    "contact.form.successMessage": "Vielen Dank für Ihre Nachricht. Wir werden uns so schnell wie möglich bei Ihnen melden.",
    "contact.office": "Öffnungszeiten",
    "contact.workdays": "Montag - Freitag",
    "contact.weekend": "Samstag - Sonntag",
    "contact.closed": "Geschlossen",

    // Documentation page
    "docs.title": "Dokumentation und Anleitungen",
    "docs.subtitle": "Unsere Dokumentation hilft Ihnen, Life Key optimal zu nutzen.",
    "docs.gettingStarted": "Erste Schritte",
    "docs.account": "Konto erstellen und erste Schritte",
    "docs.2fa": "Zwei-Faktor-Authentifizierung einrichten",
    "docs.firstDoc": "Erstes Dokument erstellen",
    "docs.recipient": "Empfänger hinzufügen",
    "docs.management": "Dokumentenverwaltung",
    "docs.types": "Dokumententypen und ihre Verwendung",
    "docs.templates": "Vorlagen für verschiedene Zwecke",
    "docs.encryption": "Verschlüsselung und Dokumentensicherheit",
    "docs.organization": "Dokumentenorganisation",

    // FAQ page
    "faq.title": "Häufig gestellte Fragen",
    "faq.noResponse": "Was passiert, wenn ich nicht auf die Check-in-Nachricht antworte?",
    "faq.noResponseAnswer": "Wenn Sie nicht auf die Check-in-Nachricht antworten, wird das System versuchen, Sie wiederholt über verschiedene Kanäle (E-Mail, SMS) zu kontaktieren. Wenn Sie innerhalb der festgelegten Zeit nicht antworten, wird das Sicherheitsprotokoll aktiviert.",
    "faq.frequency": "Wie oft erhalte ich Check-in-Nachrichten?",
    "faq.frequencyAnswer": "Sie können die Häufigkeit der Check-in-Nachrichten nach Ihren Wünschen einstellen. Standardmäßig ist sie auf alle 30 Tage eingestellt.",
  },
  cs: {
    "home.hero.title": "Zabezpečte své digitální dědictví",
    "home.hero.subtitle": "Životní klíč vám umožňuje bezpečně uchovávat a sdílet důležité informace s vámi vybranými osobami v případě nouze.",
    "home.button.getStarted": "Začít používat",
    "home.button.howItWorks": "Jak to funguje",
    "home.features.title": "Komplexní řešení pro vaše digitální dědictví",
    "home.features.subtitle": "Životní klíč poskytuje všechny nástroje, které potřebujete k zabezpečení vašich digitálních aktiv a informací.",
    "home.feature.documents": "Bezpečné dokumenty",
    "home.feature.documents.description": "Vytvářejte a spravujte šifrované dokumenty s důležitými informacemi:",
    "home.feature.activity": "Kontrola aktivity",
    "home.feature.activity.description": "Pravidelné ověřování vaší aktivity zajistí, že vaše informace zůstanou v bezpečí:",
    "home.feature.contacts": "Správa příjemců",
    "home.feature.contacts.description": "Definujte, kdo a za jakých okolností získá přístup k vašim dokumentům:",
    "home.howItWorks.title": "Jak Životní klíč funguje",
    "home.howItWorks.subtitle": "Jednoduchý a bezpečný proces ve třech krocích",
    "home.step.one": "Vytvořte dokumenty",
    "home.step.one.description": "Vytvořte dokumenty s důležitými informacemi, přístupovými údaji a instrukcemi.",
    "home.step.two": "Nastavte příjemce",
    "home.step.two.description": "Určete, kdo má mít přístup ke kterým dokumentům v případě nouze.",
    "home.step.three": "Pravidelně potvrzujte",
    "home.step.three.description": "Systém vás bude pravidelně kontaktovat. Při dlouhodobé neaktivitě se spustí bezpečnostní protokol.",
    "home.blog.title": "Nejnovější články",
    "home.blog.subtitle": "Přečtěte si naše nejnovější články o digitálním dědictví a bezpečnosti",
    "home.blog.viewAll": "Zobrazit všechny články",
    "home.cta.title": "Zabezpečte své digitální dědictví ještě dnes",
    "home.cta.subtitle": "Vytvořte si účet a začněte chránit svá digitální aktiva a informace pro své blízké.",
    "home.cta.freeAccount": "Vytvořit bezplatný účet",
    "home.cta.premium": "Zobrazit prémiové funkce",
    "document.list.title": "Moje dokumenty",
    "document.types.household": "Domácnost",
    "document.types.finance": "Finance",
    "document.types.crypto": "Kryptoměny",
    "document.types.family": "Rodina",
    "document.types.instructions": "Instrukce",
    "document.edit.title": "Upravit dokument",
    "document.edit.name": "Název dokumentu",
    "document.edit.description": "Popis dokumentu",
    "document.edit.type": "Typ dokumentu",
    "document.edit.template": "Použít šablonu",
    "document.edit.content": "Obsah dokumentu",
    "document.edit.cancel": "Zrušit",
    "document.edit.save": "Uložit změny",
    "document.edit.saved": "Dokument uložen",
    "document.edit.savedDescription": "Váš dokument byl úspěšně uložen.",
    "document.edit.templateApplied": "Šablona aplikována",
    "document.edit.templateAppliedDescription": "Obsah dokumentu byl aktualizován podle šablony",
    "common.back": "Zpět",

    // Account page
    "account.title": "Můj účet",
    "account.personalInfo": "Osobní údaje",
    "account.name": "Jméno a příjmení",
    "account.email": "Email",
    "account.phone": "Telefonní číslo",
    "account.subscription": "Plán předplatného",
    "account.editProfile": "Upravit profil",
    "account.security": "Bezpečnost",
    "account.password": "Heslo",
    "account.lastChanged": "Naposledy změněno",
    "account.2fa": "Dvoufaktorové ověření",
    "account.active": "Aktivní",
    "account.changePassword": "Změnit heslo",
    "account.2faSettings": "Nastavení 2FA",
    "account.settings": "Nastavení",
    "account.notifications": "Notifikace a upozornění",
    "account.privacy": "Soukromí a sdílení",
    "account.phoneVerification": "Ověření telefonu",
    "account.subscriptionStatus": "Předplatné",
    "account.validUntil": "Platné do",
    "account.manageSubscription": "Spravovat předplatné",

    // Contact page
    "contact.title": "Kontaktujte nás",
    "contact.subtitle": "Máte otázky nebo potřebujete pomoc? Vyplňte kontaktní formulář a my se vám ozveme co nejdříve.",
    "contact.form.name": "Vaše jméno",
    "contact.form.email": "Váš email",
    "contact.form.subject": "Předmět",
    "contact.form.message": "Vaše zpráva",
    "contact.form.submit": "Odeslat zprávu",
    "contact.form.success": "Zpráva odeslána",
    "contact.form.successMessage": "Děkujeme za vaši zprávu. Odpovíme co nejdříve.",
    "contact.office": "Provozní doba",
    "contact.workdays": "Pondělí - Pátek",
    "contact.weekend": "Sobota - Neděle",
    "contact.closed": "Zavřeno",

    // Documentation page
    "docs.title": "Dokumentace a návody",
    "docs.subtitle": "Naše dokumentace vám pomůže využít plný potenciál služby Životní klíč.",
    "docs.gettingStarted": "Začínáme se službou",
    "docs.account": "Vytvoření účtu a první kroky",
    "docs.2fa": "Nastavení dvoufaktorového ověření",
    "docs.firstDoc": "Vytvoření prvního dokumentu",
    "docs.recipient": "Přidání příjemce",
    "docs.management": "Správa dokumentů",
    "docs.types": "Typy dokumentů a jejich použití",
    "docs.templates": "Šablony pro různé účely",
    "docs.encryption": "Šifrování a bezpečnost dokumentů",
    "docs.organization": "Organizace dokumentů",

    // FAQ page
    "faq.title": "Časté dotazy",
    "faq.noResponse": "Co se stane, když nereaguji na kontrolní zprávu?",
    "faq.noResponseAnswer": "Pokud nereagujete na kontrolní zprávu, systém se pokusí kontaktovat vás opakovaně různými kanály (e-mail, SMS). Pokud nebudete reagovat po definovanou dobu, spustí se bezpečnostní protokol.",
    "faq.frequency": "Jak často budu dostávat kontrolní zprávy?",
    "faq.frequencyAnswer": "Frekvenci kontrolních zpráv si můžete nastavit podle vlastních preferencí. Standardně je nastavena na každých 30 dní.",
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'sk',
  setLanguage: () => {},
  t: () => '',
  languages: []
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('sk');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
