
import React, { createContext, useContext, useState, useEffect } from "react";

type Language = {
  code: string;
  name: string;
  nativeName: string;
};

export const languages: Language[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
];

type TranslationsType = {
  [key: string]: {
    [key: string]: string;
  };
};

// Sample translations for demonstration purposes
const translations: TranslationsType = {
  // Document edit translations
  "document.edit.title": {
    en: "Edit Document",
    de: "Dokument bearbeiten",
    fr: "Modifier le document",
    es: "Editar documento",
    it: "Modifica documento",
    sk: "Upraviť dokument",
    cs: "Upravit dokument",
    hu: "Dokumentum szerkesztése",
    pl: "Edytuj dokument",
    pt: "Editar documento",
    hi: "दस्तावेज़ संपादित करें",
    zh: "编辑文档",
    ja: "ドキュメントを編集",
  },
  "document.edit.name": {
    en: "Document Name",
    de: "Dokumentname",
    fr: "Nom du document",
    es: "Nombre del documento",
    it: "Nome del documento",
    sk: "Názov dokumentu",
    cs: "Název dokumentu",
    hu: "Dokumentum neve",
    pl: "Nazwa dokumentu",
    pt: "Nome do documento",
    hi: "दस्तावेज़ का नाम",
    zh: "文档名称",
    ja: "ドキュメント名",
  },
  "document.edit.description": {
    en: "Description",
    de: "Beschreibung",
    fr: "Description",
    es: "Descripción",
    it: "Descrizione",
    sk: "Popis",
    cs: "Popis",
    hu: "Leírás",
    pl: "Opis",
    pt: "Descrição",
    hi: "विवरण",
    zh: "描述",
    ja: "説明",
  },
  "document.edit.type": {
    en: "Document Type",
    de: "Dokumenttyp",
    fr: "Type de document",
    es: "Tipo de documento",
    it: "Tipo di documento",
    sk: "Typ dokumentu",
    cs: "Typ dokumentu",
    hu: "Dokumentum típusa",
    pl: "Typ dokumentu",
    pt: "Tipo de documento",
    hi: "दस्तावेज़ प्रकार",
    zh: "文档类型",
    ja: "ドキュメントタイプ",
  },
  "document.edit.content": {
    en: "Document Content",
    de: "Dokumentinhalt",
    fr: "Contenu du document",
    es: "Contenido del documento",
    it: "Contenuto del documento",
    sk: "Obsah dokumentu",
    cs: "Obsah dokumentu",
    hu: "Dokumentum tartalma",
    pl: "Zawartość dokumentu",
    pt: "Conteúdo do documento",
    hi: "दस्तावेज़ सामग्री",
    zh: "文档内容",
    ja: "ドキュメント内容",
  },
  "document.edit.save": {
    en: "Save Changes",
    de: "Änderungen speichern",
    fr: "Enregistrer les modifications",
    es: "Guardar cambios",
    it: "Salva modifiche",
    sk: "Uložiť zmeny",
    cs: "Uložit změny",
    hu: "Változtatások mentése",
    pl: "Zapisz zmiany",
    pt: "Salvar alterações",
    hi: "परिवर्तन सहेजें",
    zh: "保存更改",
    ja: "変更を保存",
  },
  "document.edit.cancel": {
    en: "Cancel",
    de: "Abbrechen",
    fr: "Annuler",
    es: "Cancelar",
    it: "Annulla",
    sk: "Zrušiť",
    cs: "Zrušit",
    hu: "Mégsem",
    pl: "Anuluj",
    pt: "Cancelar",
    hi: "रद्द करें",
    zh: "取消",
    ja: "キャンセル",
  },
  "document.edit.template": {
    en: "Select Template",
    de: "Vorlage auswählen",
    fr: "Sélectionner un modèle",
    es: "Seleccionar plantilla",
    it: "Seleziona modello",
    sk: "Vyberte šablónu",
    cs: "Vyberte šablonu",
    hu: "Sablon kiválasztása",
    pl: "Wybierz szablon",
    pt: "Selecionar modelo",
    hi: "टेम्पलेट चुनें",
    zh: "选择模板",
    ja: "テンプレートを選択",
  },
  "document.edit.preview": {
    en: "Preview Template",
    de: "Vorschau der Vorlage",
    fr: "Aperçu du modèle",
    es: "Vista previa de la plantilla",
    it: "Anteprima del modello",
    sk: "Náhľad šablóny",
    cs: "Náhled šablony",
    hu: "Sablon előnézete",
    pl: "Podgląd szablonu",
    pt: "Visualizar modelo",
    hi: "टेम्पलेट प्रिव्यू",
    zh: "预览模板",
    ja: "テンプレートプレビュー",
  },
  "common.back": {
    en: "Back",
    de: "Zurück",
    fr: "Retour",
    es: "Volver",
    it: "Indietro",
    sk: "Späť",
    cs: "Zpět",
    hu: "Vissza",
    pl: "Powrót",
    pt: "Voltar",
    hi: "वापस",
    zh: "返回",
    ja: "戻る",
  },
  // Document types
  "document.types.household": {
    en: "Household",
    de: "Haushalt",
    fr: "Ménage",
    es: "Hogar",
    it: "Casa",
    sk: "Domácnosť",
    cs: "Domácnost",
    hu: "Háztartás",
    pl: "Gospodarstwo domowe",
    pt: "Lar",
    hi: "घरेलू",
    zh: "家庭",
    ja: "家庭",
  },
  "document.types.finance": {
    en: "Finance",
    de: "Finanzen",
    fr: "Finance",
    es: "Finanzas",
    it: "Finanza",
    sk: "Financie",
    cs: "Finance",
    hu: "Pénzügy",
    pl: "Finanse",
    pt: "Finanças",
    hi: "वित्त",
    zh: "财务",
    ja: "金融",
  },
  "document.types.crypto": {
    en: "Cryptocurrency",
    de: "Kryptowährung",
    fr: "Cryptomonnaie",
    es: "Criptomoneda",
    it: "Criptovaluta",
    sk: "Kryptomena",
    cs: "Kryptoměna",
    hu: "Kriptovaluta",
    pl: "Kryptowaluta",
    pt: "Criptomoeda",
    hi: "क्रिप्टोकरेंसी",
    zh: "加密货币",
    ja: "暗号通貨",
  },
  "document.types.family": {
    en: "Family",
    de: "Familie",
    fr: "Famille",
    es: "Familia",
    it: "Famiglia",
    sk: "Rodina",
    cs: "Rodina",
    hu: "Család",
    pl: "Rodzina",
    pt: "Família",
    hi: "परिवार",
    zh: "家族",
    ja: "家族",
  },
  "document.types.instructions": {
    en: "Instructions",
    de: "Anweisungen",
    fr: "Instructions",
    es: "Instrucciones",
    it: "Istruzioni",
    sk: "Inštrukcie",
    cs: "Instrukce",
    hu: "Utasítások",
    pl: "Instrukcje",
    pt: "Instruções",
    hi: "निर्देश",
    zh: "指示",
    ja: "手順",
  },
  // Editor translations
  "editor.visualMode": {
    en: "Visual Editor",
    de: "Visueller Editor",
    fr: "Éditeur visuel",
    es: "Editor visual",
    it: "Editor visivo",
    sk: "Vizuálny editor",
    cs: "Vizuální editor",
    hu: "Vizuális szerkesztő",
    pl: "Edytor wizualny",
    pt: "Editor visual",
    hi: "विज़ुअल एडिटर",
    zh: "可视化编辑器",
    ja: "ビジュアルエディタ",
  },
  "editor.markdownMode": {
    en: "Markdown",
    de: "Markdown",
    fr: "Markdown",
    es: "Markdown",
    it: "Markdown",
    sk: "Markdown",
    cs: "Markdown",
    hu: "Markdown",
    pl: "Markdown",
    pt: "Markdown",
    hi: "मार्कडाउन",
    zh: "Markdown",
    ja: "マークダウン",
  },
  "editor.default": {
    en: "Default",
    de: "Standard",
    fr: "Par défaut",
    es: "Predeterminado",
    it: "Predefinito",
    sk: "Predvolené",
    cs: "Výchozí",
    hu: "Alapértelmezett",
    pl: "Domyślny",
    pt: "Padrão",
    hi: "डिफ़ॉल्ट",
    zh: "默认",
    ja: "デフォルト",
  },
  "editor.red": {
    en: "Red",
    de: "Rot",
    fr: "Rouge",
    es: "Rojo",
    it: "Rosso",
    sk: "Červená",
    cs: "Červená",
    hu: "Piros",
    pl: "Czerwony",
    pt: "Vermelho",
    hi: "लाल",
    zh: "红色",
    ja: "赤",
  },
  "editor.blue": {
    en: "Blue",
    de: "Blau",
    fr: "Bleu",
    es: "Azul",
    it: "Blu",
    sk: "Modrá",
    cs: "Modrá",
    hu: "Kék",
    pl: "Niebieski",
    pt: "Azul",
    hi: "नीला",
    zh: "蓝色",
    ja: "青",
  },
  "editor.green": {
    en: "Green",
    de: "Grün",
    fr: "Vert",
    es: "Verde",
    it: "Verde",
    sk: "Zelená",
    cs: "Zelená",
    hu: "Zöld",
    pl: "Zielony",
    pt: "Verde",
    hi: "हरा",
    zh: "绿色",
    ja: "緑",
  },
  "editor.yellow": {
    en: "Yellow",
    de: "Gelb",
    fr: "Jaune",
    es: "Amarillo",
    it: "Giallo",
    sk: "Žltá",
    cs: "Žlutá",
    hu: "Sárga",
    pl: "Żółty",
    pt: "Amarelo",
    hi: "पीला",
    zh: "黄色",
    ja: "黄色",
  },
  "editor.purple": {
    en: "Purple",
    de: "Lila",
    fr: "Violet",
    es: "Púrpura",
    it: "Viola",
    sk: "Fialová",
    cs: "Fialová",
    hu: "Lila",
    pl: "Fioletowy",
    pt: "Roxo",
    hi: "बैंगनी",
    zh: "紫色",
    ja: "紫",
  },
  "document.edit.savedDescription": {
    en: "Your document has been saved successfully",
    de: "Ihr Dokument wurde erfolgreich gespeichert",
    fr: "Votre document a été enregistré avec succès",
    es: "Su documento ha sido guardado exitosamente",
    it: "Il tuo documento è stato salvato con successo",
    sk: "Váš dokument bol úspešne uložený",
    cs: "Váš dokument byl úspěšně uložen",
    hu: "A dokumentumot sikeresen elmentettük",
    pl: "Twój dokument został pomyślnie zapisany",
    pt: "Seu documento foi salvo com sucesso",
    hi: "आपका दस्तावेज़ सफलतापूर्वक सहेजा गया है",
    zh: "您的文档已成功保存",
    ja: "ドキュメントが正常に保存されました",
  },
  "document.edit.saved": {
    en: "Document Saved",
    de: "Dokument gespeichert",
    fr: "Document enregistré",
    es: "Documento guardado",
    it: "Documento salvato",
    sk: "Dokument uložený",
    cs: "Dokument uložen",
    hu: "Dokumentum mentve",
    pl: "Dokument zapisany",
    pt: "Documento salvo",
    hi: "दस्तावेज़ सहेज लिया गया",
    zh: "文档已保存",
    ja: "ドキュメントが保存されました",
  },
  "document.edit.templateApplied": {
    en: "Template Applied",
    de: "Vorlage angewendet",
    fr: "Modèle appliqué",
    es: "Plantilla aplicada",
    it: "Modello applicato",
    sk: "Šablóna aplikovaná",
    cs: "Šablona použita",
    hu: "Sablon alkalmazva",
    pl: "Szablon zastosowany",
    pt: "Modelo aplicado",
    hi: "टेम्पलेट लागू किया गया",
    zh: "已应用模板",
    ja: "テンプレートが適用されました",
  },
  "document.edit.templateAppliedDescription": {
    en: "Template has been applied",
    de: "Die Vorlage wurde angewendet",
    fr: "Le modèle a été appliqué",
    es: "La plantilla ha sido aplicada",
    it: "Il modello è stato applicato",
    sk: "Šablóna bola aplikovaná",
    cs: "Šablona byla použita",
    hu: "A sablon alkalmazva lett",
    pl: "Szablon został zastosowany",
    pt: "O modelo foi aplicado",
    hi: "टेम्पलेट लागू कर दिया गया है",
    zh: "模板已被应用",
    ja: "テンプレートが適用されました",
  },
  "document.edit.attachments": {
    en: "Attachments",
    de: "Anhänge",
    fr: "Pièces jointes",
    es: "Archivos adjuntos",
    it: "Allegati",
    sk: "Prílohy",
    cs: "Přílohy",
    hu: "Mellékletek",
    pl: "Załączniki",
    pt: "Anexos",
    hi: "अनुलग्नक",
    zh: "附件",
    ja: "添付ファイル",
  },
  "document.edit.attachFile": {
    en: "Attach File",
    de: "Datei anhängen",
    fr: "Joindre un fichier",
    es: "Adjuntar archivo",
    it: "Allega file",
    sk: "Priložiť súbor",
    cs: "Připojit soubor",
    hu: "Fájl csatolása",
    pl: "Dołącz plik",
    pt: "Anexar arquivo",
    hi: "फ़ाइल अनुलग्न करें",
    zh: "附加文件",
    ja: "ファイルを添付",
  },
  "document.edit.insertIntoDocument": {
    en: "Insert into document",
    de: "In Dokument einfügen",
    fr: "Insérer dans le document",
    es: "Insertar en el documento",
    it: "Inserisci nel documento",
    sk: "Vložiť do dokumentu",
    cs: "Vložit do dokumentu",
    hu: "Beszúrás a dokumentumba",
    pl: "Wstaw do dokumentu",
    pt: "Inserir no documento",
    hi: "दस्तावेज में डालें",
    zh: "插入到文档",
    ja: "ドキュメントに挿入",
  },
  "document.edit.removeAttachment": {
    en: "Remove attachment",
    de: "Anhang entfernen",
    fr: "Supprimer la pièce jointe",
    es: "Eliminar archivo adjunto",
    it: "Rimuovi allegato",
    sk: "Odstrániť prílohu",
    cs: "Odstranit přílohu",
    hu: "Melléklet eltávolítása",
    pl: "Usuń załącznik",
    pt: "Remover anexo",
    hi: "अनुलग्नक हटाएं",
    zh: "删除附件",
    ja: "添付ファイルを削除",
  },
};

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  languages: Language[];
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
  languages: [],
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem("lifekey-language");
    return savedLanguage || navigator.language.split("-")[0] || "en";
  });

  useEffect(() => {
    localStorage.setItem("lifekey-language", language);
  }, [language]);

  const translate = (key: string): string => {
    if (!translations[key]) {
      return key;
    }

    return translations[key][language] || translations[key].en || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t: translate,
        languages,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};
