// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfxwclhvtqmuqwzuzlhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmeHdjbGh2dHFtdXF3enV6bGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTExODUsImV4cCI6MjA2MDM2NzE4NX0.KgWmVi56cx23zyX6QvrRikzpqbbtDwg7to-1w-nhfKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);